export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_ERROR="AUTHENTICATION_ERROR";
export const ADD_USER_SUCCESS="ADD_USER_SUCCESS";
export const ADD_USER_ERROR="ADD_USER_ERROR";
export const EXIT_SUCCESS="EXIT_SUCCESS";
